# Generated by Django 5.2.6 on 2025-10-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogapi', '0002_breed_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('TY', 'Tiny'), ('SL', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], default='MD', max_length=10),
        ),
    ]
